name: Metrics
on:
  # Update setiap jam 00:00 UTC (07:00 WIB)
  schedule: [{cron: "0 0 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  # Update saat ada push ke branch master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # === BAGIAN PENTING ===
          user: Adamibnualfatahh
          template: classic
          
          # Di sini kuncinya: Kita hanya panggil "activity" di base.
          # Header, repositories, community, metadata KITA HAPUS.
          base: activity
          
          config_timezone: Asia/Jakarta
          
          # === PENGATURAN BAHASA ===
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_threshold: 0%
          # Menampilkan grafik batang agar lebih visual
          plugin_languages_details: lines, percentage 
